### PR TITLE
feat: add official arch linux stack and pacman, drop: crystal-linux stack and ame

### LINKED ISSUE #3: Testing replacing Crystal Linux with Arch Linux
...or remove them.

### PR DESCRIPTION
**Pull request by ghost**
Added in pacman packager manager and Arch linux stack. 

Note: pacman does not support autoremove orphaned packages as a single command. Command used will only list the orphaned packages.

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution. We were recently discussing internally about this (it would be indeed nice to use the official image).

In the past, we had issues in the official image with the signing key/keyring (being outdated) so we switched to Crystal Linux. Now, we have decided to revert this change at #3 (since Crystal Linux development has become stale). Can you remove them in this same PR?

---

Previously, we used the base (latest) image, seems like multilib is more suitable for a wide variety of applications so IG this is fine. The official repository recommends some dependencies to be installed in the container by default https://github.com/archlinux/archlinux-docker/blob/master/README.md#dependencies if possible can you add them to the stack here?

I will try to test the same later today.

**Comment by ghost** [comment]
I have now removed the stack for crystal-linux and the ame package mangager. 

As for the dependencies, I believe these are in reference too building the arch linux image manually and not packages that are required to be installed within the container. 

It does however mention that the pacman lsign key isnt included in the image and the command 'pacman-key --init' should be run on the first execution of the container. https://github.com/archlinux/archlinux-docker/blob/master/README.md#principles This may render Arch Linux unviable to have as a default in the vanilla apx configs as it would require the end user knowing that this needs to be run.

**Comment by kbdharun** [comment]
> I have now removed the stack for crystal-linux and the ame package mangager.

Thanks

> It does however mention that the pacman lsign key isnt included in the image and the command 'pacman-key --init' should be run on the first execution of the container. https://github.com/archlinux/archlinux-docker/blob/master/README.md#principles This may render Arch Linux unviable to have as a default in the vanilla apx configs as it would require the end user knowing that this needs to be run.

We might need to add support for passing commands in the stack, so that it would run automatically when the subsystem is started in Apx. I will discuss with the team and get back to this. (In Apx v1, we did this for a few containers I think)

**Comment by mirkobrombin** [comment]
> on the first execution of the container

so, if I understand this correctly, we need a list of commands that should run on the first execution only? Or is it fine to always run that when the container starts?

**Comment by kbdharun** [comment]
> so, if I understand this correctly, we need a list of commands that should run on the first execution only? Or is it fine to always run that when the container starts?

I think it should be executed only once during init (first initialization of the container).

Ref. https://github.com/archlinux/archlinux-docker/blob/master/README.md#principles

**Comment by mirkobrombin** [comment]
> > so, if I understand this correctly, we need a list of commands that should run on the first execution only? Or is it fine to always run that when the container starts?
> 
> I think it should be executed only once during init (first initialization of the container).
> 
> Ref. https://github.com/archlinux/archlinux-docker/blob/master/README.md#principles

In that case it would be better to just fork the image and add a script that runs once, since adding that functionality to apx is a bit out of scope, in my opinion, there is dbox for this case. Something like this:

```bash
#!/bin/bash

EXEC_FILE="/var/lib/pacman/.init_done"
if [ ! -f "$EXEC_FILE" ]; then
  echo "First time execution of pacman-key --init..."
  pacman-key --init
  touch "$EXEC_FILE"
fi
```

**Comment by kbdharun** [comment]
> In that case it would be better to just fork the image and add a script that runs once, since adding that functionality to apx is a bit out of scope, in my opinion, there is dbox for this case.

Noted, will experiment with it later today.

**Comment by ghost** [comment]
I have made a fork of the arch image to test with and added in a .sh script which runs the code you provided as the entrypoint. However it seems when you first start/ enter this container the script doesn't run when being run by distrobox. If i run the container in podman manually the script works fine.  

For reference my image is:  docker.io/eccl3s/arch-yay:2024.06.28

From the distrobox documentation is the pacman-key --init command not something that would be better placed being passed into the --init-hooks or pre_init_hooks flag when the container is run, like the additional packages?
https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md

**Comment by kbdharun** [comment]
Sorry, forgot to make an update last week.

> I have made a fork of the arch image to test with and added in a .sh script which runs the code you provided as the entrypoint. However it seems when you first start/ enter this container the script doesn't run when being run by distrobox. If i run the container in podman manually the script works fine.

Yep, I had the same issue when testing it at https://github.com/kbdharun/vos-arch-image-test, Distrobox didn't execute the init scripts but I was able to execute it from Podman.

---

IG we can ship your PR as it is now, as all packages I tested work fine without this key, for advanced users I will document this command in the handbook in future.

---

**_Offtopic_**: Regarding pre-installing `yay` as suggested by a community member, in my testing it was very problematic and unreliable too (and in past has broken containers too), so IG this is something I can manually document in handbook too instead of defining them in the stack.

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
